### ISSUE TITLE
NOT WORKING

### ISSUE THREAD

**Issue by shanghua521** [Jordan231111/BluestacksRoot#1]
I manually modify VDI and VHD to Normal. When I use adb to copy files to the system partition, it will report read only. When I close BlueStacks, VDI and VHD will return to Readonly，so fucking terrible

**Comment by Jordan231111** [comment]
While I understand your frustration, please refrain from using profanity. It hinders our ability to collaborate effectively and find a solution.
Additionally, making such modifications manually may lead to strange bugs and complaining about bluestacks program mechanics of not saving files if they are open is way beyond scope
The best approach is to run the script again with admin while all processes related to bluestacks are closed.
