### ISSUE TITLE
help please

### ISSUE THREAD

**Issue by 123Sanyam123** [Jordan231111/BluestacksRoot#2]
Root Options:                  | Unroot Options:                | Other Options:
1. Apply BlueStacks Android 9  | 3. Undo BlueStacks Android 9   | 5. Force Custom BlueStacks Path
2. Apply BlueStacks Android 11 | 4. Undo BlueStacks Android 11  | Current Path: E:\BlueStacks_nxt

Enter option number: 2
SUCCESS: The process "HD-MultiInstanceManager.exe" with PID 45892 has been terminated.
SUCCESS: The process "HD-Player.exe" with PID 56088 has been terminated.
SUCCESS: The process "BstkSVC.exe" with PID 55868 has been terminated.
SUCCESS: The process "BstkSVC.exe" with PID 49288 has been terminated.
File not found - E:\BlueStacks_nxt\bluestacks.conf.tmp
Automatically detecting... please run the cloned instance you wish to root and close it before proceeding

Detecting the cloned instance to root...
--------------------------------------------------------------------------
The program detected Rvc64

The program will root: Rvc64
BLUESTACKS_PATH is set to: E:\BlueStacks_nxt\
Excluded path: E:\BlueStacks_nxt\
Excluded path: C:\Users\sanya\DOWNLO~1\
Changes applied successfully.
If you suspect bluestacks.conf file was corrupted, please choose undo both writable and root immediately
Exclusion removed for path: C:\Users\sanya\DOWNLO~1\
Press any key to continue . . .

this error came while running the script. What to do?

**Comment by Jordan231111** [comment]
That's no error instance is currently rooted already. If you use root checker
