### ISSUE TITLE
Opening multiple instances (fixed)

### ISSUE THREAD

**Issue by notkojak** [Jordan231111/BluestacksRoot#3]
Hello, when I root one instance, I can't open another instance I have an error

**Comment by Jordan231111** [comment]
This is more of a limitation on how bluestacks is structured, the best I can suggest for now is to keep all instance rooted if u need root. Utilize magisk hide and HMA if needed etc.

**Comment by Jordan231111** [comment]
> Hello, when I root one instance, I can't open another instance I have an error

Check the new video and repo readme
https://youtu.be/LOhKGxuhLrU

**Comment by Jordan231111** [comment]
Fixed on https://github.com/Jordan231111/BluestacksRoot/commit/ff0924a628d0613c47525bbd2bd57555666a245e

**Comment by Jordan231111** [comment]
Note: Fixed via latest release in case you haven't checked.

**Comment by Jordan231111** [comment]
Fully fixed on v7 release https://github.com/Jordan231111/BluestacksRoot/releases/tag/v7
